### ISSUE TITLE
pip install doesnt work

### ISSUE THREAD

**Issue by veiro** [sebischair/Lbl2Vec#1] opened 2022-01-27 15:27 UTC
Hello
I'm trying to install the package but I get an error.

pip install lbl2vec

Collecting lbl2vec
  ERROR: Could not find a version that satisfies the requirement lbl2vec (from versions: none)
ERROR: No matching distribution found for lbl2vec

I searched a bit on google and couldn't find a solution.

Python 3.7.4
pip 19.2.3

**Comment by TimSchopf** [comment] 2022-01-27 16:42
I assume this is caused by an incompatible Python version. Lbl2Vec requires `Python>=3.8`. Could you upgrade your Python version and then try again?

**Comment by TimSchopf** [comment] 2022-02-15 08:17
Closing this issue, because there is no answer yet and upgrading the Python version should solve it.

**Closed as completed by TimSchopf** 2022-02-15 08:17 UTC
Labels: help wanted
